services:
  mysql:
    image: mysql:8
    container_name: cnpm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cnpm
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  backend:
    image: maven:3.9-eclipse-temurin-17
    container_name: cnpm-backend
    working_dir: /app
    volumes:
      - ./Backend:/app
    command: sh -c "mvn clean package -DskipTests && java -jar target/*.jar"
    ports:
      - "9090:9090"
    depends_on:
      - mysql

  frontend:
    image: node:18
    container_name: cnpm-frontend
    working_dir: /app
    volumes:
      - ./FrontEnd:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
